[core]
reloadable = true
order = 0

[package]
version = "2.3.6"
category = "Simulation"
title = "Omniverse MJCF Importer"
description = "MJCF Importer"
repository="https://gitlab-master.nvidia.com/isaac/mjcf-importer-extension"
authors = ["Isaac Sim Team"]
keywords = ["mjcf", "mujoco", "importer", "isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
icon = "data/icon.png"
writeTarget.kit = true
preview_image = "data/preview.png"

[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.window.filepicker" = {}
"omni.kit.window.content_browser" = {}
"omni.kit.pip_archive" = {} # pulls in pillow
"omni.kit.commands" = {}
"omni.kit.window.extensions" = {}
"omni.kit.window.property" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.tool.asset_importer" = {}
"omni.kit.helper.file_utils" = {}
"omni.usd.schema.physx" = {}
"omni.usd.libs" = {}

[[python.module]]
name = "isaacsim.asset.importer.mjcf"

[[python.module]]
name = "isaacsim.asset.importer.mjcf.tests"

[[native.plugin]]
path = "bin/*.plugin"
recursive = false


[[test]]

# this is to catch issues where our assimp is out of sync with the one that comes with
# asset importer as this can cause segfaults due to binary incompatibility.

stdoutFailPatterns.exclude = [
    "*Cannot find material with name*",
    "*Neither inertial nor geometries where specified for*",
    "*JointSpec type free not yet supported!*",
    "*is not a valid usd path*",
    "*extension object is still alive, something holds a reference on it*", # exclude warning as failure

]

args = ["--/app/file/ignoreUnsavedOnExit=1"]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
