[core]
reloadable = true
order = 0

[package]
version = "2.2.1"
category = "Simulation"
title = "Omniverse MJCF Importer"
description = "MJCF Importer"
repository="https://gitlab-master.nvidia.com/isaac/mjcf-importer-extension"
authors = ["Isaac Sim Team"]
keywords = ["mjcf", "mujoco", "importer", "isaac"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
writeTarget.kit = true
preview_image = "data/preview.png"

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.0.0. Replaced by isaacsim.asset.importer.mjcf"


[dependencies]
"isaacsim.asset.importer.mjcf" = {}


[[python.module]]
name = "omni.importer.mjcf"
